version: "2.2"

services:
  postgres:
    image: postgres:11.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: elastic_bot
    volumes:
      - ./pg/init.sql:/docker-entrypoint-initdb.d/1-init-data.sql
    ports:
      - "5432:5432"
